parameters:
    jerive.container_profiler.class: Jerive\Bundle\ContainerExplorerBundle\DataCollector\ContainerDataCollector

services:
    jerive.container_profiler:
        class: %jerive.container_profiler.class%
        tags:
          - name: data_collector
            template: JeriveContainerExplorerBundle:Collector:index
            id: container